# <div class="alert alert-block alert-info" dir="rtl" style="text-align: center;"><strong><span style="font-size: 20pt">NumPy Tutorial <br /></span></strong></div>

In [1]:
import numpy as np

# How to create Arrays in NumPy

In [2]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# How to return chosen elements

In [3]:
print(np.where(a > 4, 'Py', 11))

[['11' '11' '11']
 ['11' 'Py' 'Py']
 ['Py' 'Py' 'Py']]


This can be used on multidimensional arrays too:

In [4]:
print(np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]]))

[[1 8]
 [3 4]]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


# Shape and Reshape in NumPy
The numpy. reshape() function allows us to reshape an array in Python. Reshaping basically means, changing the shape of an array. And the shape of an array is determined by the number of elements in each dimension.

In [6]:
print(a.shape)

(3, 3)


In [7]:
print(type(a.shape))

<class 'tuple'>


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]]) 
print(b.shape)

(2, 3)


In [9]:
print(np.reshape(b, (3, 2)))

[[1 2]
 [3 4]
 [5 6]]


# Flatten Vs. Ravel
Return a copy of the array collapsed into one dimension.


In [10]:
c = np.array([[1,2], [3,4]])
print(c.flatten())

[1 2 3 4]


In [11]:
np.ravel(c)

array([1, 2, 3, 4])

# Flatten
1 - Return copy of the original array.

2 - If you modify any value of this array value of the original array is not affected.

3 - Flatten() is comparatively slower than ravel() as it occupies memory.

4 - Flatten is a method of an ndarray object. Let us check out the difference in this code.

# Ravel

1 - Return only reference/view of the original array.

2 - If you modify the array you would notice that the value of the original array also changes.

3 - Ravel is faster than flatten() as it does not occupy any memory.

4 - Ravel is a library-level function. 

In [12]:
print(np.reshape(c, (1, -1)))  # -1 means the number of columns will be determined automatically

[[1 2 3 4]]


In [13]:
print(np.reshape(c, (-1, 1)))  # -1 means the number of rows will be determined automatically

[[1]
 [2]
 [3]
 [4]]


# ndim 
ndim() function return the number of dimensions of an array.

In [14]:
print(a.ndim)

2


In [15]:
print(a.size)  # number of elements

9


# arange (A - range) in NumPy :)
 The arange() function is used to get evenly spaced values within a given interval.

In [16]:
d = np.arange(1, 20, step=4)
print(d)

[ 1  5  9 13 17]


# linspace in NumPy
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval.

The endpoint of the interval can optionally be excluded.

In [17]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [19]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

# Creating Specific Arrays


In [20]:
print(np.ones(shape=(3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


 - `np.zeros`
# <img src="https://www.w3resource.com/w3r_images/numpy-array-zeros-function-image-a.png" /> 

In [21]:
print(np.zeros(shape=(2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print(np.full((3, 2), 5))

[[5 5]
 [5 5]
 [5 5]]


 - `np.eye`
# <img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1.png" /> 

In [23]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(np.fliplr(a))                 #Reverse the order of elements along axis 1 (left/right).

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [26]:
print(np.random.rand(3, 2)) 

[[0.23830563 0.12876318]
 [0.17461437 0.27297759]
 [0.55752956 0.1975696 ]]


# Operations on NumPy Arrays

# <img src="https://numpy.org/devdocs/_images/np_sub_mult_divide.png" /> 


In [27]:
e = np.array([[10, 20], [30, 40]], dtype=np.float64)
f = np.array([[50, 60], [70, 80]], dtype=np.float64)

print(e)
print()
print(f)

[[10. 20.]
 [30. 40.]]

[[50. 60.]
 [70. 80.]]


In [28]:
print(np.add(e, f))         # Add arguments element-wise.
print()
print(e + f)                # The + operator can be used as a shorthand for np.add on ndarrays.

[[ 60.  80.]
 [100. 120.]]

[[ 60.  80.]
 [100. 120.]]


In [29]:
print(np.subtract(e, f))    # Subtract arguments, element-wise.
print()
print(e - f)                # The - operator can be used as a shorthand for np.subtract on ndarrays.

[[-40. -40.]
 [-40. -40.]]

[[-40. -40.]
 [-40. -40.]]


In [30]:
print(np.multiply(e, f))    # Multiply arguments element-wise.
print()
print(e * f)                # The * operator can be used as a shorthand for np.multiply on ndarrays.

[[ 500. 1200.]
 [2100. 3200.]]

[[ 500. 1200.]
 [2100. 3200.]]


In [31]:
print(np.divide(e, f))      # Divide arguments element-wise.
print()
print(e / f)                # The / operator can be used as a shorthand for np.divide on ndarrays.

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
print(np.sqrt(e))           # Elementwise square root

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


# Sorting Elements

In [33]:
g = np.array([2, 87, 10, 0, 7, 4, 15, 10])
print(np.sort(g))

[ 0  2  4  7 10 10 15 87]


# Concatenate in NumPy
Join a sequence of arrays along an existing axis

In [34]:
h = np.array([11, 12, 13, 14, 15, 17])
i = np.array([18, 12, 19, 20, 22, 23])
print(np.concatenate((h, i)))

[11 12 13 14 15 17 18 12 19 20 22 23]


# Adding Elements
All the input arrays must have same number of dimensions.

In [35]:
print(np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Removing Elements
All the input arrays must have same number of dimensions.

In [36]:
j = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(j, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [37]:
j = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(j, 1, 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

# More useful array operations


# <img src="https://numpy.org/devdocs/_images/np_matrix_aggregation.png" /> 

In [38]:
k = np.array([10, 20, 30, 40, 50])
print(k)

[10 20 30 40 50]


In [39]:
k.sum()

150

In [40]:
k.min()

10

In [41]:
k.max()

50

In [42]:
k.mean()

30.0

In [43]:
k.var()

200.0